version: '3.8'

services:
  drowsiness_detection:
    build:
      context: ./drowsiness_detection
      dockerfile: Dockerfile
    container_name: drowsiness_detection
    ports:
      - "5002:5002"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - FIREBASE_DATABASE_URL=https://securin-b49ed-default-rtdb.asia-southeast1.firebasedatabase.app/
      - VEHICLE_ID=SUPRAX123
    networks:
      - securin_be

  face_recognition:
    build:
      context: ./face_recognition
      dockerfile: Dockerfile
    container_name: face_recognition
    ports:
      - "5001:5001"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - FIREBASE_DATABASE_URL=https://securin-b49ed-default-rtdb.asia-southeast1.firebasedatabase.app/
      - VEHICLE_ID=SUPRAX123
      - MQTT_BROKER=broker.emqx.io
      - MQTT_PORT=1883
      - MQTT_USERNAME=    
      - MQTT_PASSWORD=
      - MQTT_CLIENT_ID=face_recognition_client
      - INTRUDER_API=http://localhost:4998
      - KNOWN_FACES_API=http://localhost:4998
    networks:
      - securin_be

networks:
  securin_be:
    external: true
