version: '3.8'

services:
  # ── BACKEND ──
  facerecognition_api:
    build:
      context: ./backend/facerecognition_api
      dockerfile: Dockerfile
    container_name: facerecognition_api
    ports:
      - "4998:4998"
    volumes:
      - ./backend/facerecognition_api/photo_storage:/app/photo_storage
    networks:
      - securin_be

  ml_forwarder:
    build:
      context: ./backend/ml_forwarder
      dockerfile: Dockerfile
    container_name: ml_forwarder
    ports:
      - "4999:4999"
    environment:
      - DROWSINESS_DETECTION_SERVICE=http://drowsiness_detection:5002/upload
      - FACE_RECOGNITION_SERVICE=http://face_recognition:5001/upload
    depends_on:
      - facerecognition_api
    networks:
      - securin_be

  # ── MACHINE LEARNING ──
  drowsiness_detection:
    build:
      context: ./ml/drowsiness_detection
      dockerfile: Dockerfile
    container_name: drowsiness_detection
    ports:
      - "5002:5002"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - FIREBASE_DATABASE_URL=https://securin-b49ed-default-rtdb.asia-southeast1.firebasedatabase.app/
      - VEHICLE_ID=SUPRAX123
    networks:
      - securin_be
    
  face_recognition:
    build:
      context: ./ml/face_recognition
      dockerfile: Dockerfile
    container_name: face_recognition
    ports:
      - "5001:5001"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - FIREBASE_DATABASE_URL=https://securin-b49ed-default-rtdb.asia-southeast1.firebasedatabase.app/
      - VEHICLE_ID=SUPRAX123
      - MQTT_BROKER=broker.emqx.io
      - MQTT_PORT=1883
      - MQTT_USERNAME=    
      - MQTT_PASSWORD=
      - MQTT_CLIENT_ID=face_recognition_client
      - INTRUDER_API=http://facerecognition_api:4998
      - KNOWN_FACES_API=http://facerecognition_api:4998
    networks:
      - securin_be

networks:
  securin_be:   
    driver: bridge